/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { sticky_scroll_active$_T } from './sticky_scroll_active$_b.js'
export interface scroll_ctx_I {
	sticky_scroll_active$?:sticky_scroll_active$_T
}