/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { _b } from '@ctx-core/object'
import type { scroll_Ctx } from './scroll_Ctx'
import type { sticky_scroll_active$_T } from './sticky_scroll_active$_b'
import { sticky_scroll_active$_b } from './sticky_scroll_active$_b'
export interface scroll_ctx_I {
	sticky_scroll_active$?:sticky_scroll_active$_T
	scroll_b_h?:scroll_b_h_T
}
export interface scroll_b_h_T {
	get sticky_scroll_active$():sticky_scroll_active$_T
}
export function scroll_b_h_b(ctx:scroll_Ctx):scroll_b_h_T {
	return _b<scroll_Ctx, 'scroll_b_h'>('scroll_b_h', ()=>{
		return {
			get sticky_scroll_active$() { return sticky_scroll_active$_b(ctx) }
		}
	})(ctx)
}